### ISSUE TITLE
export 配置错误

### ISSUE THREAD

**Issue by AlimuratYusup** [RayTang88/BeautyMaster#13]
作者您好，我大概是有两个问题，一个是您在项目里面指定的模型是InternLM吗，第二是问题是我看了大概感觉是要用InternLM，于是我就直接clone了，但是环境变量配置出现了问题。
第一幅图是环境变量配置
<img width="1301" alt="截屏2024-11-11 18 43 34" src="https://github.com/user-attachments/assets/b3d425cf-2783-4f88-9b36-f29789d4ebef">
第二幅图是报错，找不到beautymaster包
<img width="1301" alt="截屏2024-11-11 18 44 02" src="https://github.com/user-attachments/assets/ead33f2b-678f-4c7a-8401-fa64ac62ca0a">
第三幅图是关于代码部分，现在连os包都识别不了
<img width="1301" alt="截屏2024-11-11 18 33 51" src="https://github.com/user-attachments/assets/48901f0d-896a-45c0-8578-af97e79ddf7f">

**Comment by RayTang88** [comment]
1.环境变量
请参考[README.MD](https://github.com/RayTang88/BeautyMaster/blob/master/README.md#%E8%AE%BE%E7%BD%AE%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F)
1.1 MODEL_ROOT：模型的根路径，目前代码使用的VLM为MiniCPM-Llama3-V-2_5-AWQ，LLM为Qwen2-7B-Instruct-AWQ，可将https://code.openxlab.org.cn/raytang88/MiniCPM-Llama3-V-2_5-AWQ.git和https://code.openxlab.org.cn/raytang88/Qwen2-7B-Instruct-AWQ.git克隆下来，这个目录设置为MODEL_ROOT；
1.2 CODE_ROOT：clone本工程的代码的根路径；
1.3 DATA_ROOT：数据的根路径，可设置为$(CODE_ROOT)/BeautyMaster/beautymaster/openxlab_demo/simple_data，也可以参照这个格式自备；

2.设置完环境变量即可解决

3.os是python的内置模块，请查看pycharm的python环境是否配置正确
