### ISSUE TITLE
from my_get_maks import get_img_agnostic, get_img_agnostic2, get_img_agnostic3错误

### ISSUE THREAD

**Issue by AlimuratYusup** [RayTang88/BeautyMaster#14]
作者您好。当我运行如下命令时报错了python /home/featurize/work/BeautyMaster/beautymaster/demo/app.py
报错：Traceback (most recent call last):
  File "/home/featurize/work/BeautyMaster/beautymaster/demo/app.py", line 55, in <module>
    from beautymaster.demo.infer import Interface, parse_opt
  File "/home/featurize/work/BeautyMaster/beautymaster/demo/infer.py", line 8, in <module>
    from beautymaster.src.try_on import TryOnInterface
  File "/home/featurize/work/BeautyMaster/beautymaster/src/try_on.py", line 13, in <module>
    from my_get_maks import get_img_agnostic, get_img_agnostic2, get_img_agnostic3
ModuleNotFoundError: No module named 'my_get_maks'
<img width="650" alt="截屏2024-11-13 01 37 30" src="https://github.com/user-attachments/assets/102e3a92-6a5d-45c3-8958-187cb81ca23a">
这是我回溯到/home/featurize/work/BeautyMaster/beautymaster/src/try_on.py，并且修改为绝对路径，仍然报错，想问问my_get_maks包在哪里
<img width="1303" alt="截屏2024-11-13 01 40 40" src="https://github.com/user-attachments/assets/af785c2d-7c41-4a75-aadf-2b9ccd853eae">

**Comment by RayTang88** [comment]
请参考[README.MD](https://github.com/RayTang88/BeautyMaster/blob/master/README.md#%EF%B8%8F-%E4%B8%8B%E8%BD%BD%E4%BB%A3%E7%A0%81)
将指定版本的VTON代码下载到third_party目录。
