### ISSUE TITLE
An error occurred while trying to fetch /home/featurize/work/BeautyMaster/beautymaster/third_party/IDM-VTON/yisol/IDM-VTON/: Error no file named diffusion_pytorch_model.safetensors found in directory /home/featurize/work/BeautyMaster/beautymaster/third_party/IDM-VTON/yisol/IDM-VTON/.

### ISSUE THREAD

**Issue by AlimuratYusup** [RayTang88/BeautyMaster#15]
作者您好，我在指定第三方模型路径的时候遇到了一些问题
<img width="1062" alt="截屏2024-11-15 19 12 06" src="https://github.com/user-attachments/assets/40e25ec3-3ce6-4a19-8c94-053823f13441">
如上报错，发生在try_on_model_path = weight_path+"/BeautyMaster/beautymaster/third_party/IDM-VTON/yisol/IDM-VTON"
如下是我的第三方库结构，vae和unet_encode里面均有diffusion_pytorch_model.safetensors
<img width="357" alt="截屏2024-11-15 19 12 27" src="https://github.com/user-attachments/assets/949cdf84-60d9-4f32-b47e-7b7e8e25a324">
如下当我指定ry_on_model_path = weight_path+"/BeautyMaster/beautymaster/third_party/IDM-VTON/yisol/IDM-VTON/vae/"如下报错
<img width="1440" alt="截屏2024-11-15 19 26 33" src="https://github.com/user-attachments/assets/8e66ba94-c75d-4e17-a7bb-8739bd40d19c">
如下当我指定ry_on_model_path = weight_path+"/BeautyMaster/beautymaster/third_party/IDM-VTON/yisol/IDM-VTON/unet_encode/"如下报错
<img width="1440" alt="截屏2024-11-15 20 20 53" src="https://github.com/user-attachments/assets/2c40f01a-01b2-45aa-9842-87195b219eab">

**Comment by RayTang88** [comment]
请参考#17
