### ISSUE TITLE
不同作者发布的第三方库IDM-VTON该如何选择

### ISSUE THREAD

**Issue by AlimuratYusup** [RayTang88/BeautyMaster#17]
作者，您好。经过思考我认为是否是我下载的IDM-VTON与您的不同导致这个问题，我目前找到了两个版本，我该选哪个，try_on文件里面的五个文件路径该怎么指定。
<img width="1552" alt="截屏2024-11-15 21 42 26" src="https://github.com/user-attachments/assets/6612b14c-5e5e-405d-8c93-b9bdf9879e8f">
<img width="1552" alt="截屏2024-11-15 21 43 20" src="https://github.com/user-attachments/assets/141b7853-c65f-4978-9751-17a2325aeef0">
<img width="1282" alt="截屏2024-11-15 19 44 13" src="https://github.com/user-attachments/assets/2fd217c4-3dd1-461d-b507-eaae3533b911">

**Comment by RayTang88** [comment]
请参考[.gitmodules](https://github.com/RayTang88/BeautyMaster/blob/master/.gitmodules)，有指定本仓库使用的IDM-VTON

**Comment by RayTang88** [comment]
#13 相应路径设置好后，这几个路径保持代码中的设置就好
注意： VTON的权重也下载在MODEL_ROOT，这个路径下
