### ISSUE TITLE
未在readme中对"openxlab"进行环境变量设置，导致无法自动下载模型，需要动手下模型，容易下错版本

### ISSUE THREAD

**Issue by AlimuratYusup** [RayTang88/BeautyMaster#18]
![image](https://github.com/user-attachments/assets/7ceebf0b-1eaf-4f49-8cbb-d334c0866a41)
我手动设置了os.environ['openxlab'] = '1'，不然代码通不过if判断语句

**Comment by RayTang88** [comment]
代码是从另外一个分支合并过来的，那个分支的使用是在远程的服务器上需要去自动下载权重和一些环境配置，所以设置了一下这个环境变量。我们自己在本地运行，这些都可以手动下载，或者第一次让代码自动下载，后面置为False，避免每次运行都去下载，浪费时间。默认是需要手动下载的，后续会在readme里面说明下载模型的地址。
