### ISSUE TITLE
对git clone --recursive https://github.com/RayTang88/BeautyMaster.git存在一点小疑惑

### ISSUE THREAD

**Issue by AlimuratYusup** [RayTang88/BeautyMaster#20]
作者您好，当我运行您的这句代码，它不会把第三方库全部下好吗，为什么第三方库还是空的
![image](https://github.com/user-attachments/assets/b738fb28-2487-412a-9064-021d0cd2dbc8)

**Comment by RayTang88** [comment]
*.pkl ，*.pt， *.onnx类似的都是权重文件，需要专门下载，使用git clone --recursive三方库里面不会下载权重
