### ISSUE TITLE
代码中疑似发现一处错误

### ISSUE THREAD

**Issue by AlimuratYusup** [RayTang88/BeautyMaster#21]
在run_local_match方法中，interface = Interface(**vars(opt))被注释掉了，但是在后面在未创建interface对象的 前提下直接调用了interface.match_interface()
![image](https://github.com/user-attachments/assets/40bead8c-817b-425b-8b90-08416f87a787)

**Comment by RayTang88** [comment]
没有问题，我想你应该没更新最新的代码，使用了master分支的commit`f012c4c4fbea61d2a866a6fa0eea21abe8817521`之前的代码，interface还是一个全局变量（可以加速后面的调用，但是显存占用率高），可以在函数中进行调用；在最新commit的代码中将interface变成了是一个局部变量（节约显存），写法可以参考最新commit代码[interface](https://github.com/RayTang88/BeautyMaster/blob/f012c4c4fbea61d2a866a6fa0eea21abe8817521/beautymaster/demo/app.py#L180)
